export const customFont = {
  black: 'NotoSans-Black',
  blackItalic: 'NotoSans-BlackItalic',
  bold: 'NotoSans-Bold',
  boldItalic: 'NotoSans-BoldItalic',
  extraBold: 'NotoSans-ExtraBold',
  extraBoldItalic: 'NotoSans-ExtraBoldItalic',
  extraLight: 'NotoSans-ExtraLight',
  light: 'NotoSans-Light',
  italic: 'NotoSans-Italic',
  medium: 'NotoSans-Medium',
  regular: 'NotoSans-Regular',
  extra_bold: 'NotoSans-ExtraBold',
  extra_light: 'NotoSans-ExtraLight',
  semi_bold: 'NotoSans-SemiBold',
  italic: 'NotoSans-Italic',
  thin: 'NotoSans-Thin',
  thinItalic: 'NotoSans-ThinItalic',
};
