import React from 'react';
import {WD, HD} from './responsive';
import {customFont} from './custom-font';
import {StyleSheet} from 'react-native';
import COLORS from './colors';

export const globalStyles = StyleSheet.create({
  errorText: {
    color: 'red',
    marginHorizontal: WD(6),
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  boxPadding: {
    padding: WD(0),
    paddingVertical: WD(5),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headingText: {
    fontSize: WD(4.5),
    fontFamily: customFont.bold,
    color: COLORS.black,
    marginLeft: WD(4),
    marginTop: WD(10),
  },
  smallText: {
    fontSize: WD(3.5),
    fontFamily: customFont.regular,
    color: COLORS.black,
    marginHorizontal: WD(5),
    marginLeft: WD(4),
    marginTop: WD(2),
    marginBottom: WD(5),
  },
  normalText: {
    fontSize: WD(3.3),
    fontFamily: customFont.regular,
    color: COLORS.black,
  },
  normalTextGray: {
    fontSize: HD(1.8),
    fontFamily: customFont.regular,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  normalTextLightGray: {
    fontSize: HD(1.6),
    fontFamily: customFont.regular,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  subHeadingText: {
    fontSize: HD(2.3),
    fontFamily: customFont.semi_bold,
    color: COLORS.black,
  },
  subHeadingTextGray: {
    fontSize: HD(2.1),
    fontFamily: customFont.regular,
    color: 'rgba(136, 136, 136, 1)',
  },
  loginText: {
    textAlign: 'center',
    marginVertical: WD(5),
    color: COLORS.black,
    fontFamily: customFont.regular,
  },
  homeHeading: {
    fontSize: WD(4.3),
    fontFamily: customFont.semi_bold,
    color: COLORS.black,
    marginLeft: WD(5),
    marginBottom: WD(3),
  },
  heading: {
    marginTop: WD(10),
    fontSize: WD(4.5),
    fontFamily: customFont.semi_bold,
    color: COLORS.black,
  },
  line: {
    backgroundColor: COLORS.primary,
    width: WD(15),
    height: HD(0.5),
    marginLeft: WD(5),
    marginBottom: WD(5),
  },
  shopHeading: {
    fontSize: WD(4.3),
    fontFamily: customFont.medium,
    color: COLORS.black,
    marginLeft: WD(5),
    marginBottom: WD(1),
    marginTop: WD(5),
  },
  roundBtn: {
    width: WD(10),
    height: HD(5),
    marginLeft: WD(3),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    elevation: 5,
    backgroundColor: COLORS.white,
  },
  input: {
    textAlignVertical: 'top',
    color: '#888888',
    fontSize: HD(2),
    width: WD(70),
    paddingHorizontal: WD(3),
    borderRadius: 14,
    fontFamily: customFont.regular,
    color: COLORS.darkGray,
    paddingVertical: WD(3),
  },
  inputSection: {
    textAlignVertical: 'top',
    marginTop: WD(3),
    paddingTop: WD(2),
    flexDirection: 'row',
    paddingHorizontal: WD(2),
    marginLeft: WD(6),
    width: '88%',
    borderColor: '#B9B9B9',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: WD(2),
    height: HD(6),
    alignItems: 'center',
    fontFamily: customFont.regular,
    fontSize: HD(2),
  },
  crossBtn: {
    width: 50,
    position: 'absolute',
    height: 50,
    marginLeft: WD(45),
    marginTop: WD(-90),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    elevation: 10,
    backgroundColor: COLORS.white,
    padding: HD(1),
    shadowColor: COLORS.darkGray,
    shadowOpacity: 0.2,
    shadowRadius: 2,
    shadowOffset: {
      width: 2,
      height: 2,
    },
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: WD(2),
    borderBottomColor: '#d3d3d3',
    borderBottomWidth: 0.5,
    marginHorizontal: WD(3),
  },
  title: {
    fontFamily: customFont.regular,
    fontSize: WD(3.5),
    color: COLORS.dark,
    letterSpacing: 0.5,
    marginVertical: WD(2),
    marginHorizontal: WD(8),
  },
});
