const SCREENS = {
  ProductListing: 'ProductListing',
  ProductDetails: 'ProductDetails',
  Wishlist: 'Wishlist',
  AddressList: 'AddressList',
  EditAddress: 'EditAddress',
  AddAddress: 'AddAddress',
  Home: 'Home',
  Login: 'Login',
  Notifications: 'Notifications',
  Filters: 'Filters',
  Shop: 'Shop',
  Community: 'Community',
  Cart: 'Cart',
  Account: 'Account',
  ForgotPassword: 'ForgotPassword',
  RequestOTP: 'RequestOTP',
  Register: 'Register',
  OTP: 'OTP',
  OtherProductListing: 'OtherProductListing',
  Reels: 'Reels',
  SearchProducts: 'SearchProducts',
  SortingScreen: 'SortingScreen',
  EditProfile: 'EditProfile',
  EditProfileUser: 'EditProfileUser',
  ReelsFilters: 'ReelsFilters',
  SelectAddress: 'SelectAddress',
  Payment: 'Payment',
  SuccessPayment: 'SuccessPayment',
  OrderDetails: 'OrderDetails',
  Orders: 'Orders',
  CrazyDealsScreen: 'CrazyDealsScreen',
  WriteReview: 'WriteReview',
  Reviews: 'Reviews',
  AddPostByUser: 'AddPostByUser',
  EditPostByUser: 'EditPostByUser',
  BecomeSeller: 'BecomeSeller',
  BecomeSellerProfile: 'BecomeSellerProfile',
  AddImagePostByVendor: 'AddImagePostByVendor',
  AddVideoPostByVendor: 'AddVideoPostByVendor',

  EditImagePostByVendor: 'EditImagePostByVendor',
  EditVideoPostByVendor: 'EditVideoPostByVendor',
};

export default SCREENS;
